apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: s4
  namespace: ubench
  labels:
    zone: default
    app: s4
    version: "1.0"
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: s4
  replicas: 1
  
  template:
    metadata:
      labels:
        zone: default
        app: s4
        version: "1.0"
        prometheus.io/scrape: 'true'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: s4
          image: msvcbench/microservice_v3-screen:latest
          ports:
            - name: http-mubpodport
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-volume
              mountPath: /app/MSConfig
          env:
            - name: APP
              value: s4
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: PN
              value: '4'
            - name: TN
              value: '16'
          resources: 
            requests:
              cpu: 100m
            limits:
              cpu: 100m    
        
        

      

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-ms
---
apiVersion: v1
kind: Service
metadata:
  name: s4
  namespace: ubench
  labels:
    app: s4
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: http-mubserviceport
  - port: 51313
    targetPort: 51313
    name: grpc-mubserviceport
  selector:
    app: s4