apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ms
spec:
  capacity:
    storage: 100Mi
  accessModes:
#    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  nfs:
    server: 192.168.100.158
    path: /kubedata/mubSharedData
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-ms
  namespace: ubench
spec:
  accessModes:
    - ReadOnlyMany # Access modes for volumes is defined under Persistent Volumes
  #storageClassName: slow
  resources:
    requests:
      storage: 50Mi # volume size requested